# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(000006)
$foreground = rgb(D2D9E3)
$color0 = rgb(000006)
$color1 = rgb(1F2936)
$color2 = rgb(374253)
$color3 = rgb(174978)
$color4 = rgb(5A444A)
$color5 = rgb(5B697E)
$color6 = rgb(5E6E82)
$color7 = rgb(B6C0CE)
$color8 = rgb(7F8690)
$color9 = rgb(2A3648)
$color10 = rgb(4A586E)
$color11 = rgb(1F62A0)
$color12 = rgb(785B63)
$color13 = rgb(798CA8)
$color14 = rgb(7E92AE)
$color15 = rgb(B6C0CE)
