# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# For window rules and layerrules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# This file is used to add or overwrite window rules 
# This file will not be modified during dotfiles updates

## GeForce NOW 
# Capture GeForceNOW client
windowrule = match:class ^(GeForceNOW)$, tag +gfn
windowrule = match:initial_class ^(GeForceNOW)$, tag +gfn

# Float to avoid issues with tiling
windowrule = match:tag gfn, float 1

# Force set size
windowrule = match:tag gfn, size 1920 1080

#windowrule = match:tag gfn, keep_aspect_ratio 1

# Prevent going in fullscreen mode 
#windowrule = suppressevent fullscreen maximize fullscreenoutput, tag:gfn*
#windowrule = suppressevent fullscreenoutput, tag:gfn*

# Set window max size, so even if it tried to full screen it will still be no in fullscreen
#windowrule = maxsize 1920 1080, tag:gfn*

windowrule = match:tag gfn, center 1

## Spotify
windowrule {
  name = spotify
  match:class = ^(spotify)$
  opacity = 0.9 0.7
}
